voiceflow/libs

- packages/general-types/src/nodes/setV2.ts
**Fixes or implements VF-914**
> feat: set value type (VF-914)

- packages/api-sdk/src/models/version.ts
**Fixes or implements VF-1069**
Optional buttons property that is going to be either "stacked" or "carousel"
> fix: prototype buttons property (VF-1069)

- packages/general-types/src/nodes/interaction.ts
- packages/general-types/src/nodes/types.ts
- packages/general-types/src/request/index.ts
- packages/general-types/src/types.ts
- packages/general-types/src/version/settings.ts
> fix: button types (VF-000)

- packages/api-sdk/src/models/apiKey.ts
> fix: api key project id (VF-000)

- packages/api-sdk/src/models/version.ts
**Fixes or implements VF-1177**
> feat: add platform to prototype (VF-1177)

- packages/alexa-types/package.json
- packages/alexa-types/src/nodes/cancelPayment.ts
- packages/alexa-types/src/nodes/capture.ts
- packages/alexa-types/src/nodes/interaction.ts
- packages/alexa-types/src/nodes/reminder.ts
- packages/general-types/src/nodes/interaction.ts
- packages/general-types/src/nodes/types.ts
- packages/general-types/src/types.ts
- packages/google-types/src/nodes/interaction.ts
- yarn.lock
**Fixes or implements VF-1251**
> feat: add ability to have reprompts and else at the same time (VF-1251)

- packages/general-types/src/types.ts
> fix: make nomatch type nullable

- packages/google-types/src/nodes/df-es/payload.ts
- packages/google-types/src/nodes/df-es/types.ts
- packages/google-types/src/nodes/index.ts
**Fixes or implements VF-1233**
Payload df es step
Merge before service and runtime PR
| google-service | [link](https://github.com/voiceflow/google-service) |
| google-runtime     | [link](https://github.com/voiceflow/google-runtime) |
> feat: payload df es step (VF-1233)

- packages/api-sdk/src/models/program.ts
**Fixes or implements VF-1301**
added `name` field for programs
I also added a `versionID` field - for future migrations, we should definitely be using `versionID` instead of `skillID` in the future
both fields are optional.
> feat: add flow names to programs (VF-1301)

- packages/google-types/src/constants/intents.ts
- packages/google-types/src/constants/locales.ts
- packages/google-types/src/constants/slots.ts
- packages/google-types/src/constants/voices.ts
- packages/google-types/src/project/index.ts
- packages/google-types/src/project/member.ts
- packages/google-types/src/version/index.ts
- packages/google-types/src/version/publishing.ts
- packages/google-types/src/version/settings.ts
**Fixes or implements VF-1204**
DF ES Specific types to facilitate the work on the new DF ES endpoints in google service ([here](https://github.com/voiceflow/google-service/pull/106))
PS: Locales list and Publishing fields are going to be updated soon, just copy-pasting them for now from their google counterpart
| google-service | [link](https://github.com/voiceflow/google-service/pull/106)
> feat: dialogflow es types (VF-1204)

- .circleci/config.yml
- lerna.json
- packages/api-sdk/package.json
> ci: sem rel messages

- packages/general-types/package.json
- packages/general-types/src/nodes/index.ts
- packages/general-types/src/nodes/text.ts
- packages/general-types/src/nodes/types.ts
- yarn.lock
**Fixes or implements VF-1361**
> feat: text step types (VF-1361)

- packages/general-types/src/nodes/text.ts
> feat: add variable types

- packages/api-sdk/src/resources/base.ts
- packages/api-sdk/src/resources/crud.ts
- packages/api-sdk/src/resources/diagram.ts
- packages/api-sdk/src/resources/program.ts
- packages/api-sdk/src/resources/project/index.ts
- packages/api-sdk/src/resources/project/member.ts
- packages/api-sdk/src/resources/version.ts
> feat: improve api-sdk typings

- packages/base-types/src/node/buttons.ts
- packages/base-types/src/node/constants.ts
- packages/base-types/src/node/index.ts
- packages/base-types/src/node/text.ts
- packages/base-types/src/node/utils/base.ts
- packages/base-types/src/node/utils/event.ts
- packages/base-types/src/request/action.ts
- packages/base-types/src/request/index.ts
- packages/chat-types/src/node/buttons.ts
- packages/voice-types/src/node/buttons.ts
> feat: add buttons types (VF-000)

- packages/api-sdk/src/models/shared.ts
- packages/chat-types/src/types.ts
- packages/chat-types/src/version/index.ts
- packages/voice-types/src/types.ts
- packages/voice-types/src/version/index.ts
> feat: chat intent input type (VF-000)

- packages/api-sdk/src/resources/analytics.ts
- packages/api-sdk/src/resources/apiKey.ts
- packages/api-sdk/src/resources/base.ts
- packages/api-sdk/src/resources/diagram.ts
- packages/api-sdk/src/resources/fetcher.ts
- packages/api-sdk/src/resources/index.ts
- packages/api-sdk/src/resources/program.ts
- packages/api-sdk/src/resources/project/index.ts
- packages/api-sdk/src/resources/project/member.ts
- packages/api-sdk/src/resources/user.ts
- packages/api-sdk/src/resources/version.ts
- packages/api-sdk/tests/resources/_crud.unit.ts
- packages/api-sdk/tests/resources/analytics.unit.ts
- packages/api-sdk/tests/resources/apiKey.unit.ts
- packages/api-sdk/tests/resources/base.unit.ts
- packages/api-sdk/tests/resources/prototypeProgram.unit.ts
- packages/api-sdk/tests/resources/user.unit.ts
> feat: analytics resource

- packages/google-dfes-types/src/constants/voices.ts
**Fixes or implements VF-1638**
Swedish was accidentally mapped to Slovak, updated.
> fix: swedish was mapped to slovakia (VF-1638)

- packages/base-types/src/request/index.ts
> feat: add request label (VF-000)

- packages/base-types/src/trace/index.ts
**Fixes or implements VF-1294**
Also should make enum of all the debug types.
I think the only concern is if this is gonna look awkward or something:
```
{
type: 'debug',
payload: {
type: 'some kinda debug type',
message: 'stuff here'
}
}
```
> fix: add type to debug (VF-1294)

- packages/base-types/src/node/_v1.ts
- packages/base-types/src/node/ifV2.ts
- packages/base-types/src/node/utils/trace.ts
**Fixes or implements VF-1524**
We need to send the label of the condition through the trace, and to do that it needs to be included in the compiled node.
Updated the IfV2 to use the same path types as the _v1 block
> fix: label for if ports (VF-1524)

- packages/api-sdk/package.json
- packages/api-sdk/src/client.ts
- packages/api-sdk/src/index.ts
- packages/api-sdk/src/publicclient.ts
- packages/api-sdk/src/resources/analytics.ts
- packages/api-sdk/src/resources/fetcher.ts
- packages/api-sdk/src/resources/user.ts
- packages/api-sdk/src/utils/index.ts
- packages/api-sdk/src/utils/struct.ts
- packages/api-sdk/tests/resources/analytics.unit.ts
- packages/api-sdk/tests/resources/apiKey.unit.ts
- packages/api-sdk/tests/resources/user.unit.ts
- packages/api-sdk/tests/utils.unit.ts
- yarn.lock
**Fixes or implements VF-1641**
https://github.com/voiceflow/creator-api/pull/771
> feat: add analytics encryption (VF-1641)

- packages/general-types/src/constants/index.ts
- packages/general-types/src/constants/platformType.ts
**Fixes or implements VF-1544**
- Adds `PlatformType` enum from voiceflow/internal
- Adds & improves on `TTSPlatformType` enum from voiceflow/general-service
> feat(general-types): add PlatformType and TTSPlatformType (VF-1544)

- packages/alexa-types/package.json
- packages/api-sdk/package.json
- packages/google-dfes-types/package.json
- packages/google-types/package.json
- yarn.lock
**Fixes or implements VF-1621**
Upgraded `@voiceflow/common` package version.
N/A
N/A
N/A
N/A
> fix: bump @voiceflow/common (VF-1621)

- packages/general-types/src/constants/platformType.ts
**Fixes or implements VF-1545**
> fix: rename dialogflow es const (VF-1545)

- packages/api-sdk/src/models/diagram.ts
- packages/api-sdk/src/models/version.ts
- packages/base-types/src/node/component.ts
- packages/base-types/src/node/constants.ts
- packages/base-types/src/node/jump.ts
**Fixes or implements VF-1826**
add types related to the topics feature
> feat: add topics types (VF-1826)

- packages/base-types/src/node/visual.ts
**Fixes or implements VF-1779**
Add options object to ImageStepData
https://github.com/voiceflow/general-service/pull/153
> feat: add gif loop options (VF-1779)

- packages/general-types/src/constants/platformType.ts
**Fixes or implements VF-1892**
> feat: split df es into voice and chat (VF-1892)

- packages/base-types/src/node/utils/trace.ts
- packages/base-types/src/trace/index.ts
**Fixes or implements VF-1901**
add no reply response trace type
> feat: add no reply response trace (VF-1901)

- packages/base-types/src/node/utils/trace.ts
- packages/base-types/src/trace/index.ts
> fix: Revert "feat: add no reply response trace (VF-1901)" VF-1901

- packages/api-sdk/package.json
- yarn.lock
**update common package version VF-000**
> fix: update common package (VF-000)

- packages/api-sdk/package.json
- packages/api-sdk/src/resources/user.ts
- packages/api-sdk/src/utils/struct.ts
- packages/api-sdk/tests/resources/user.unit.ts
- packages/api-sdk/tests/utils.unit.ts
- yarn.lock
**Fixes or implements VF-1926**
Reverts 8c1f0bde79a118c37a3e203ab8268350c8ff3dcd introduced in #66
> fix: revert common crypto in jwt (VF-1926)

- packages/google-dfes-types/src/constants/locales.ts
> fix: updates dfes locales (VF-000)

- packages/api-sdk/.eslintrc.js
- packages/api-sdk/package.json
- packages/api-sdk/src/resources/user.ts
- packages/api-sdk/src/utils/struct.ts
- packages/api-sdk/tests/client.unit.ts
- packages/api-sdk/tests/index.unit.ts
- packages/api-sdk/tests/resources/user.unit.ts
- packages/api-sdk/tests/utils.unit.ts
- yarn.lock
BREAKING CHANGES: use JWT to parse authentication tokens
replace the `atob` and custom JWT parse method with the official `jsonwebtoken.decode` method.
So the original reason why `atob` was implemented, was because it doesn't care about the "header" property of the token, because tokens are going to start with a 16 character "userHash" appended to the front of the JWT string.
`jsonwebtoken.decode` does not work if the `userHash` is infront.
To merge this PR, just to be safe I wanted to account for both cases: with `userHash` and without the `userHash` prefix, although it is very unlikely that we will be passed a token with no `userHash`. This is because creator-api's middleware REQUIRES `userHash` to actually resolve a token: …
> perf: jwt parse token (VF-000)

- packages/api-sdk/package.json
- yarn.lock
Bumps dependency `tsconfig-paths`.
> fix(deps): bump dependency to test circleci workflow (VF-000)

- .github/workflows/rebase.yaml
- .github/workflows/rebase_all.yaml
**Part or VF-2005**
This fixes the comment spam on most PRs caused by the outdated action version on the recently added rebasing workflows.
> ci: bump rebase action version (VF-2005)

- packages/alexa-types/src/node/interaction.ts
**Fixes or implements VF-2141**
add goto data to node
> fix: go-to alexa (VF-2141)

- packages/api-sdk/src/resources/project/index.ts
- packages/api-sdk/tests/resources/project/index.unit.ts
i think this is all i need to do to add a new function to api-sdk?
> feat: get version v2 (VF-000)

- packages/google-types/src/node/interaction.ts
**Fixes or implements VF-2142**
goto node type
> feat: goto google actions (VF-2142)

- packages/base-types/src/models/shared.ts
- packages/base-types/src/node/ifV2.ts
- packages/base-types/src/node/utils/noMatch.ts
> fix: if types

- packages/general-types/src/constants/slot.ts
**Fixes or implements VF-159**
lots and lots of slot types:
- VF-159
- VF-160
- VF-161
- VF-162
- VF-163
- VF-165
- VF-166
- voiceflow/luis-authoring-service#103
- voiceflow/creator-app#4566
> feat: more slot types (VF-159)

- packages/base-types/src/models/project.ts
> feat: add project version (VF-000)

- packages/common/src/utils/generate.ts
- packages/common/src/utils/index.ts
**Fixes or implements VF-2339**
Migrate generate utils [from creator-app](https://github.com/voiceflow/creator-app/blob/master/packages/ui/src/utils/generate.ts)
> feat: add generate utils (VF-2339)

- packages/base-types/src/node/capture.ts
capture blocks have an optional intent that can be triggered for going straight into DM
> fix: intent on capture node (VF-000)

- packages/base-types/src/node/capture.ts
> fix: pass slot data in capture (VF-000)

- packages/base-types/src/request/index.ts
> fix: no reply request (VF-000)

- packages/api-sdk/src/resources/analytics.ts
- packages/api-sdk/tests/resources/analytics.unit.ts
> fix: track is sync return promise (VF-000)

- packages/common/src/utils/functional.ts
> feat: utils updates (VF-000)

- packages/base-types/src/models/shared.ts
> chore: convert types to interfaces (VF-000)

- packages/metrics/.depcheckrc
- packages/metrics/.eslintignore
- packages/metrics/.eslintrc.js
- packages/metrics/.nycrc.json
- packages/metrics/CHANGELOG.md
- packages/metrics/README.md
- packages/metrics/config/tests/mocharc.yml
- packages/metrics/package.json
- packages/metrics/sonar-project.properties
- packages/metrics/src/client/index.ts
- packages/metrics/src/index.ts
- packages/metrics/src/testing/MetricsAsserter.ts
- packages/metrics/src/testing/createBaseConfig.ts
- packages/metrics/src/testing/index.ts
- packages/metrics/tests/.eslintrc.js
- packages/metrics/tests/client/index.unit.ts
- packages/metrics/tests/setup.ts
- packages/metrics/tsconfig.build.json
- packages/metrics/tsconfig.json
- packages/metrics/yarn.lock
- yarn.lock
**Fixes or implements VF-1458**
DRY ftw
> feat(metrics): create `@voiceflow/metrics` package (VF-1458)

- packages/alexa-types/src/node/capture.ts
- packages/alexa-types/src/node/captureV2.ts
- packages/alexa-types/src/node/index.ts
- packages/base-types/src/node/capture.ts
- packages/base-types/src/node/captureV2.ts
- packages/base-types/src/node/constants.ts
- packages/base-types/src/node/index.ts
- packages/chat-types/src/node/capture.ts
- packages/chat-types/src/node/captureV2.ts
- packages/chat-types/src/node/index.ts
- packages/general-types/src/node/capture.ts
- packages/general-types/src/node/captureV2.ts
- packages/general-types/src/node/index.ts
- packages/google-types/src/node/capture.ts
- packages/google-types/src/node/captureV2.ts
- packages/google-types/src/node/index.ts
- packages/voice-types/src/node/capture.ts
- packages/voice-types/src/node/captureV2.ts
- packages/voice-types/src/node/index.ts
**Fixes or implements VF-2456**
> fix: capture v2 (VF-2456)

- packages/google-types/src/version/index.ts
> fix: google model version

- packages/metrics/package.json
set the package access to be public, didn't realize it was private until now
> fix: set metrics access to public (VF-000)

- packages/base-types/src/models/project.ts
- packages/base-types/src/node/text.ts
- packages/base-types/src/version/settings.ts
add a messageDelay prop to text steps, allowing users to customize the delay messages get returned in prototype
> feat: add props for message delay (VF-000)

- packages/api-sdk/package.json
- packages/api-sdk/src/fetch.ts
- packages/api-sdk/tests/fetch.unit.ts
- packages/metrics/package.json
- yarn.lock
**Fixes or implements VF-2629**
Update `axios` to `v0.24` to remove security warnings
> chore(deps): update axios (VF-2629)

- packages/base-types/src/models/project.ts
- packages/base-types/src/node/text.ts
mike wants it to be in ms now, also no need to the enabled flag anymore
> feat: change to ms (VF-000)

- packages/chat-types/src/version/settings.ts
- packages/general-types/src/version/settings.ts
> fix: move to chat types (VF-000)

- packages/chat-types/src/version/settings.ts
mike wants 1500ms , 1s too fast
> fix: default delay to 1500ms (VF-000)

- packages/common/src/crypto/index.ts
> fix: added murmurhash export

- yarn.lock
> fix: yarn.lock update (VF-2617)

- packages/common/src/utils/intent.ts
- packages/common/tests/fixtures/name.json
- packages/common/tests/utils/intent.unit.ts
- packages/common/tsconfig.json
Given utterances and entities, generate various utterances for entities.
Move it from `luis-authoring-service` because other exports need the same thing. This is a refactored version of:
https://github.com/voiceflow/luis-authoring-service/blob/f963754f3bb8518ee6524c6b62f6e9acd48adceb/lib/jobs/publish/utils/helpers.ts#L15-L98
> fix: utterance permutations (VF-000)

- packages/common/src/constants/runtime.ts
- yarn.lock
**Fixes or implements VF-2810**
adding a VF_DM_PREFIX constant for use in `general-runtime` and `general-service`
> feat: adding a 'dm_' variable to constants (VF-2810)

- packages/common/src/constants/index.ts
**Fixes or implements VF-2810**
exporting runtime from constants file
> feat: added export line in constants file for dm. (VF-2810)

- packages/base-types/src/node/buttons.ts
- packages/base-types/src/node/interaction.ts
> feat: add diagramID to go-to intent (VF-000)

- package.json
- packages/common/package.json
- packages/common/src/types.ts
- packages/common/src/utils/array.ts
- packages/metrics/package.json
- yarn.lock
> fix: update typescript (VF-000)

- packages/google-types/src/constants/intents.ts
**Fixes or implements VF-2440**
added constants for google-types in libs/packages/google-types
> feat: split up google intents and status intents in google-types constants (VF-2440)

- packages/google-types/src/constants/intents.ts
**Fixes or implements VF-2440**
added a typeguard function to use in google-service for VF-2440
> feat: added a google-types typeguard function for google-service (VF-2440)

- packages/google-types/src/constants/intents.ts
**Fixes or implements VF-2440**
adding a few more samples for the google built ins
> fix: added additional utterances for google intent projcets (VF-2440)

- packages/alexa-types/src/node/cancelPayment.ts
- packages/alexa-types/src/node/payment.ts
- packages/alexa-types/src/node/reminder.ts
- packages/alexa-types/src/node/stream.ts
- packages/alexa-types/src/node/userInfo.ts
- packages/base-types/src/models/base/node.ts
- packages/base-types/src/models/base/port.ts
- packages/base-types/src/node/_v1.ts
- packages/base-types/src/node/api.ts
- packages/base-types/src/node/buttons.ts
- packages/base-types/src/node/capture.ts
- packages/base-types/src/node/captureV2.ts
- packages/base-types/src/node/code.ts
- packages/base-types/src/node/exit.ts
- packages/base-types/src/node/googleSheets.ts
- packages/base-types/src/node/if.ts
- packages/base-types/src/node/ifV2.ts
- packages/base-types/src/node/interaction.ts
- packages/base-types/src/node/prompt.ts
- packages/base-types/src/node/random.ts
- packages/base-types/src/node/stream.ts
- packages/base-types/src/node/utils/base.ts
- packages/base-types/src/node/zapier.ts
- packages/google-types/src/node/stream.ts
> feat: improve ports typings (VF-000)

- packages/exception/README.md
- https://github.com/voiceflow/XXXXXXXXX/pull/123
> fix: release exception with built assets (vf-000)

- packages/base-types/src/models/diagram.ts
- https://github.com/voiceflow/XXXXXXXXX/pull/123
> fix: deprecate diagram children (CT-000)

- packages/base-types/src/models/project/index.ts
- packages/base-types/src/models/project/knowledgeBase.ts
changing the structure to support a settings field
> fix: knowledge base settings (LLM-001)

- packages/api-sdk/src/resources/version/index.ts
- packages/base-types/src/models/version/index.ts
**Fixes or implements CV3-149**
expose version variable states through `api-sdk`
- https://github.com/voiceflow/creator-api/pull/1260
> feat: add new version variable state list endpoint (CT-2093)

- packages/common/src/utils/object/common.ts
- packages/common/src/utils/object/deepMap.ts
- packages/common/tests/utils/object/deepMap.unit.ts
- https://github.com/voiceflow/XXXXXXXXX/pull/123
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test
> fix: deep map (CT-000)
