voiceflow/libs

- packages/general-types/src/nodes/visual.ts
**Fixes or implements [VF-894](https://voiceflow.atlassian.net/browse/VF-894)**
Add in hidden type for `CanvasVisibility` enum. Needed for the new image select options.
| creator_app | [https://github.com/voiceflow/creator-app/pull/3407](https://github.com/voiceflow/creator-app/pull/3407) |
> feat: add hidden property to canvasVisibility (VF-894)

- packages/general-types/src/constants/slot.ts
**Fixes or implements [VF-975](https://voiceflow.atlassian.net/browse/VF-975?atlOrigin=eyJpIjoiZTJhNDBhOWY4NDJhNGEyODhmMTc5YmM1MjQ3OTYyMDgiLCJwIjoiaiJ9)**
Adds plain 10-digit (`1234567890`, area code + phone number) and 13-digit (`1234568790123`, country code + area code + phone number) phone numbers to the training data array.
> fix(general-types): add plain 10-digit and 13-digit phone numbers to training data (VF-975)

- packages/general-types/src/nodes/types.ts
- packages/general-types/src/trace/index.ts
Versa needed a new trace type for knowing when it goes out an "else" port in the choice block, or how exactly an intent gets handled.
> fix: path trace type (VF-000)

- packages/api-sdk/package.json
**Fixes or implements VF-483**
Only publish the `build/` folder and other required files to npm.
| https://github.com/voiceflow/common/pull/46 | [link](https://github.com/voiceflow/common/pull/46) |
| https://github.com/voiceflow/logger/pull/23     | [link](https://github.com/voiceflow/logger/pull/23) |
| https://github.com/voiceflow/libs/pull/25     | [link](https://github.com/voiceflow/libs/pull/25) |
| https://github.com/voiceflow/general-runtime/pull/137     | [link](https://github.com/voiceflow/general-runtime/pull/137) |
> fix(api-sdk): only publish build folder (VF-483)

- packages/api-sdk/src/resources/user.ts
Stop assuming that tokens are in the proper format, otherwise you get these errors:
> fix(api-sdk): handle bad input to `parseJWT` function (VF-000)

- packages/base-types/src/text/index.ts
**Fixes or implements VF-1255**
we'll add background color attribute to markup text node
> feat(base-types): adds background color to base text (VF-1255)

- packages/api-sdk/src/models/version.ts
- packages/api-sdk/src/resources/version.ts
Fixes or implements VF-1856
Brief description. What is this change?
Today we have this feature available on voiceflow desktop app. We want to enable it to our creator-app. So we're creating an endpoint to generate the responses for given versionID diagrams. That response will be use to download a csv file.
> feat: adds export project version responses api method (VF-1856)

- .gitignore
- packages/base-types/src/index.ts
- packages/base-types/src/models/apiKey.ts
- packages/base-types/src/models/diagram.ts
- packages/base-types/src/models/index.ts
- packages/base-types/src/models/member.ts
- packages/base-types/src/models/program.ts
- packages/base-types/src/models/project.ts
- packages/base-types/src/models/shared.ts
- packages/base-types/src/models/utils.ts
- packages/base-types/src/models/version.ts
- sonar-project.properties
**Fixes or implements VF-1912**
Move the model types from api-sdk to base-types and converting the types from being defined by superstructs to regular TS.
> fix: move model types from api-sdk to base-types (VF-1912)

- packages/api-sdk/src/types.ts
deprecate usage of the `ArrayElement` type, it should be replace with index type syntax
> fix: deprecate `ArrayElement` (VF-000)

- .circleci/continue-config.yml
**Fixes or implements VF-2167**
Bumps orb version to add API trigger for published lerna tags from https://github.com/voiceflow/orb-common/pull/50
> ci: bump orb version to add API trigger for published lerna tags (VF-2167)

- packages/base-types/src/trace/index.ts
Export TraceType with the Trace object
We are using TraceType in our code but the import is not exposed to any top level and so we had to import like so:
```typescript
import { TraceType } from '@voiceflow/base-types/build/node/utils'; 
```
This will move it so we can use it like this:
```typescript
import { Trace } from "@voiceflow/base-types";
...
switch(trace.type) {
case Trace.TraceType.TEXT: 
...
break;
case Trace.TraceType.SPEAK: 
...
break;
```
**NOTE:** if you have a better way to check a trace's type please let me know!
> feat: export TraceType In Trace (VF-000)

- packages/api-sdk/src/resources/analytics.ts
- packages/api-sdk/tests/resources/analytics.unit.ts
**Implements VF-2464**
Support for batch segment tracking calls for the api.
When using `batchTrack` method, with `batching` option enabled, all calls made in the same tick, will be sent as a single request.
These new endpoints have been implemented on this PR: https://github.com/voiceflow/creator-api/pull/878
> feat: support batch for segment tracking (VF-2464)

- packages/metrics/src/testing/MetricsAsserter.ts
some services (ex. realtime) don't use the client factory type of `(config: Config) => Client`, they use `(options: { config: Config, logger: Logger })`
this leads to confusing errors during tests, where you get `Error: connect ECONNREFUSED 127.0.0.1:somerandomport`. this is because `options.PORT_METRICS` doesn't matter when the user's code is reading `options.config.PORT_METRICS`.
since the configuration value is missing it falls back to the default port of `9464`.
the server is on `9464` but the assertion tries to use `{some random port}`, which is what causes the `ECONNREFUSED` error
> fix: use stricter type for `MetricsAsserter` constructor (VF-000)

- packages/metrics/src/testing/MetricsAsserter.ts
- packages/metrics/src/testing/createBaseConfig.ts
improves the typings in `MetricsAsserter` so that users of the library never need to use type assertions when writing their unit tests.
this also includes some refactors to how the base config is used
now this is possible:
```ts
import * as VFMetrics from '@voiceflow/metrics';
import CustomMetricsClient, { CustomMetrics } from '@/lib/clients/metrics';
import { CustomConfig } from '@/types';
const metricsAsserter = new VFMetrics.Testing.MetricsAsserter<CustomMetrics, CustomConfig>((config) => CustomMetricsClient({ someCustomKey: config }));
```
> fix: improve typings of configs in `MetricsAsserter` (VF-000)

- package.json
- yarn.lock
**Fixes or implements VF-2629**
Update `@voiceflow/commitlint-config` to v2 which should remove some insecure dev dependencies that is being reported by github
> chore(deps-dev): update @voiceflow/commitlint-config to v2 (VF-2629)

- package.json
- packages/base-types/package.json
- yarn.lock
**Fixes or implements VF-2629**
Upgrade `slate` dependency to `v0.72`
> chore(deps): update slate to v0.72 (VF-2629)

- packages/api-sdk/src/resources/analytics.ts
- packages/api-sdk/tests/resources/analytics.unit.ts
It merges `batchTrack` and `track` methods into just `track`. It will batch the request when `batching` is enabled.
This way we don't have refactor all the calls from `.track` to  `.batchTrack`, making it easier to use.
This is a breaking change since .batchTrack will not exist anymore, but since this method was only published a couple weeks ago and we are using in less than 10 places, not sure if we need to publish a major.
renamed `batchTrack` to `track` and original `track` became the private method `_send`.
> feat: merge batchTrack and track methods into track (VF-2464)

- .gitignore
- packages/base-types/src/models/project.ts
- packages/general-types/src/version/settings.ts
since we only have it on text projects now, and its cleaner to put in settings, instead of project
> fix: move delay to general setting types (VF-000)

- packages/base-types/src/models/version.ts
need to add this, cause public getPrototype can now return this new data in it's version data
> fix: getProto return data type update (VF-000)

- packages/common/src/crypto/hex2abc.ts
- packages/common/tests/crypto/hex2abc.ts
`hex2abc('0xabc123')` becomes `gxabchij`
> feat: add `hex2abc` function (VF-000)

- packages/base-types/src/node/utils/trace.ts
- packages/base-types/src/trace/index.ts
**Fixes or implements VF-2728**
Create a new trace type, when we are asking the user explicit to fill a certain entity during entity filling from intent/choice/button/capture steps.
(i.e. What is your email?)
We don't necessarily need to consume this trace, but any NLP/NLU outside of our default one that is used in conjunction with the runtime will need this.
The trace gives the intent we are trying to fill out, and the current entity we are prompting for.
> fix: entity filling trace (VF-2728)

- packages/alexa-types/src/constants/index.ts
- packages/alexa-types/src/constants/intents.ts
- packages/alexa-types/src/constants/mappings.ts
- packages/common/src/utils/index.ts
- packages/common/src/utils/intent.ts
- packages/common/src/utils/slot.ts
**Fixes or implements VF-2613**
moved a bunch of utility functions out from services to a centralized location, and started adding in the mappings patterns with proper declarations and consistent names.
Check my comments for where they originally came from
We were using the `_invert` method to invert the array, but this has side effects because of many to one/one to many mappings. So it is better to be explicit
> fix: mapping and utilities (VF-2613)

- packages/google-types/package.json
- yarn.lock
**Fixes or implements VF-2699**
upgrades the googleapis package to the latest version
- https://github.com/voiceflow/google-service/pull/209
> fix: update googleapis version (VF-2699)

- packages/common/src/utils/array.ts
- packages/voiceflow-types/src/version/index.ts
```
type A = B[] | C[];
type D = UnionArrays<A> // => (B | C)[]
```
> fix: union types generic (VF-000)

- packages/common/src/types.ts
- packages/common/src/utils/array.ts
fixes the type of the `inferUnion` function
adds a `SafeArray` for stricter array type construction. also allows immutable arrays to be passed in.
replaces the `ArrayElem` type with a `ArrayUnionToIntersection` type to do effectively the same thing
arguably the `inferUnion` function should be renamed as in the TS ecosystem this operation is called "union to intersection" ([related](https://fettblog.eu/typescript-union-to-intersection/))
closes #186
> fix: fix types on inferUnion function (VF-000)

- packages/base-types/src/node/speak.ts
- packages/base-types/src/node/text.ts
- packages/base-types/src/node/utils/trace.ts
both speak and text traces should have a `message: string` property.
added a new optional `ai?: boolean` indicator to dictate if the response is freely generated
> fix: base response trace with ai indicator (PL-000)

- .circleci/continue-config.yml
Use latest sonarcloud orb vesrsion
> ci(sonar): use latest sonarcloud orb (IN-976)

- packages/google-types/package.json
- packages/google-types/src/models.ts
Looking in the realtime folder, googleapis is almost 100MB. That's kinda insane.
We don't even use it in any meaningful way.
> fix: google-apis is only a dev dependency (CT-000)

- .circleci/config.yml
* IN-000
* Use latest ORB version to generate config.This allows for correct change detection when merging code from master to 
prod branch hence allowing correct new images to be built
> fix: use latest orb version (IN-000)
